GET http://localhost:3001/todos

###

POST http://localhost:3001/todos/new
Content-Type: application/json

{
  "text":"Order Burger"
}

###
DELETE http://localhost:3001/todo/DELETE/63762830abefdfdcec512736

###
//here u will get true and false whenver you change send the request  
PUT http://localhost:3001/todo/complete/637625bfc51e518b898aba2a